categories:
  - title: '🚀 Features'
    label: 'feature'
  - title: '🐛 Bug Fixes'
    label: 'fix'
  - title: '🧹 Chores'
    label: 'chore'
  - title: '🧰 Maintenance'
    label: 'refactor'
  - title: '🚀 Release'
    label: 'release'
template: |
  ## Changes
  $CHANGES
